name: flutter_tech_sales
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

#version: 3.1.0+9
version: 5.0.0+11


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  uuid: ^3.0.5
  month_picker_dialog: ^0.4.0
  dropdown_search: ^2.0.1
  store_redirect: ^2.0.1
  shimmer: ^2.0.0
  path: ^1.7.0
  connectivity: ^3.0.6
  scoped_model: ^1.1.0
#  shared_preferences: ^0.5.12+4
  shared_preferences: ^2.0.12
  jwt_decoder: ^2.0.1
  tuple: ^2.0.0
  encrypt: ^5.0.1
  device_info: ^2.0.3
  get: ^4.6.1
  sms_autofill: ^2.2.0
  expandable: ^5.0.1
  pointycastle: ^3.5.0
  async: ^2.4.2
  url_launcher: ^6.0.18
  sqflite: ^2.0.2
  permission_handler: ^8.3.0
  flutter_svg: ^1.0.3
  flutter_calendar_carousel: ^1.5.3
  chewie: ^1.2.2
  syncfusion_flutter_charts: ^19.4.48
  syncfusion_flutter_datagrid: ^19.4.48
  screenshot: ^1.2.3
  syncfusion_flutter_gauges: ^19.4.48
  provider: ^5.0.0
  google_fonts: ^2.2.0
  path_provider: ^2.0.1
  http: ^0.13.4
  intl: ^0.17.0
  geolocator: ^8.0.5
  google_maps_flutter: ^2.0.0
  #  google_maps_flutter: ^2.1.1

  image_picker:
  #  image_picker: ^0.6.7+22
  #  image_picker: ^0.8.4+5


  package_info: ^2.0.2
  firebase_core:
  firebase_crashlytics: ^2.4.5
  firebase_analytics: ^9.1.0
  plugin_platform_interface: ^2.1.2
  firebase_messaging:
  firebase_core_platform_interface:
  # below plugins not used null safety
  slider_button: ^2.0.0
  data_connection_checker: ^0.3.4
  moengage_inbox: ^3.1.0
  moengage_flutter: ^4.0.2
  flutter_screenutil: ^5.1.1


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


dependency_overrides:
  geolocator: ^5.3.1
  http: ^0.12.2
  flutter_screenutil: ^0.7.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/Container.png
    - assets/images/rejected.png
    - assets/images/app_icon.png
    - assets/images/Logo(Bluebg).svg
    - assets/images/Logo(Whitebg).svg
    - assets/images/Logo(yellowbg).svg
    - assets/images/Logo(Bluebg).png
    - assets/images/Logo(Whitebg).png
    - assets/images/Logo(yellowbg).png
    - assets/images/mwp.png
    - assets/images/sr.png
    - assets/images/tutorial.png
    - assets/images/calendar.png
    - assets/images/influencer.png
    - assets/images/callcenter.png

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli-Bold.ttf
        - asset: assets/fonts/muli/Muli.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800

