name: flutter_tech_sales
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

#version: 3.1.0+9
version: 5.0.0+11


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^1.0.4
  http: ^0.12.2
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  google_fonts: ^1.1.2
  intl: ^0.17.0
  geolocator: ^5.3.1
  google_maps_flutter: ^1.2.0
  google_map_location_picker: ^3.3.4
  jwt_decoder: ^1.0.4
  tuple: ^1.0.3
  encrypt: ^4.1.0
  device_info: ^1.0.0
  get: ^3.26.0
  sms_autofill: ^1.3.1
  expandable: ^4.1.4
  pointycastle: ^2.0.1
  image_picker: ^0.6.7+22
  async: ^2.4.2
  url_launcher: ^5.7.10
  sqflite: ^1.3.2+4
  path_provider: ^1.6.28
  permission_handler: ^5.1.0+2
  flutter_svg: ^0.19.3
  flutter_calendar_carousel: 1.5.3
  chewie: ^0.12.2
  moengage_flutter: ^4.0.2
  syncfusion_flutter_charts: ^18.4.49
  syncfusion_flutter_datagrid: ^18.4.49-beta
  screenshot: ^0.3.0
  syncfusion_flutter_gauges: ^18.4.49
  flutter_screenutil: ^0.7.0
  package_info: ^0.4.3+4
  uuid: ^2.2.2
  month_picker_dialog: ^0.3.3
  dropdown_search: ^0.4.9
  store_redirect: ^1.0.2
  shimmer: ^1.1.2
  path: ^1.7.0
  connectivity: ^2.0.2
  scoped_model: ^1.1.0

  # below dependencies use for Firebase
  firebase_analytics: ^7.0.1
  firebase_core:
  firebase_crashlytics:
#    git:
#      url: git://github.com/FirebaseExtended/flutterfire.git
#      path: packages/firebase_crashlytics/firebase_crashlytics
#      ref: 200b8ca8f1c452e4249fb791e53cc55e786ac768
  plugin_platform_interface: ^2.0.0
  #firebase_messaging: ^7.0.3
  firebase_messaging: ^8.0.0-dev.14
  firebase_core_platform_interface: ^3.0.1

  # below plugins not used null safety
  slider_button: ^0.6.0
  data_connection_checker: ^0.3.4
  moengage_inbox: ^3.1.0


  # below plugins not used in app
  # autocomplete_textfield: ^1.7.3
  # dartz: ^0.10.0
  # get_it: ^7.2.0
  # unicorndial: ^1.1.5
  # video_player: ^2.2.4


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


dependency_overrides:
  intl: ^0.17.0
  firebase_core:
  geolocator: ^5.3.1
  google_maps_flutter: ^1.2.0
  plugin_platform_interface: ^2.0.0
  firebase_core_platform_interface: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/Container.png
    - assets/images/rejected.png
    - assets/images/app_icon.png
    - assets/images/Logo(Bluebg).svg
    - assets/images/Logo(Whitebg).svg
    - assets/images/Logo(yellowbg).svg
    - assets/images/Logo(Bluebg).png
    - assets/images/Logo(Whitebg).png
    - assets/images/Logo(yellowbg).png
    - assets/images/mwp.png
    - assets/images/sr.png
    - assets/images/tutorial.png
    - assets/images/calendar.png
    - assets/images/influencer.png
    - assets/images/callcenter.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli-Bold.ttf
        - asset: assets/fonts/muli/Muli.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Black.ttf
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
